"""fifth commit (add cf_rejection and driver_rejection)

Revision ID: 4e203bd56941
Revises: 612dee223b43
Create Date: 2024-04-12 23:56:48.461019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e203bd56941'
down_revision: Union[str, None] = '612dee223b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestedRide', sa.Column('driver_rejection', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('suggestedRide', sa.Column('cf_rejection', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestedRide', 'cf_rejection')
    op.drop_column('suggestedRide', 'driver_rejection')
    # ### end Alembic commands ###
