"""third commit (add driver_con,cf_con,finished)

Revision ID: 612dee223b43
Revises: b268efdb349d
Create Date: 2024-04-11 21:07:34.690832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612dee223b43'
down_revision: Union[str, None] = 'b268efdb349d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestedRide', sa.Column('driver_confirmation', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('suggestedRide', sa.Column('cf_confirmation', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('suggestedRide', sa.Column('finished', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestedRide', 'finished')
    op.drop_column('suggestedRide', 'cf_confirmation')
    op.drop_column('suggestedRide', 'driver_confirmation')
    # ### end Alembic commands ###
