"""second commit (add driver_id)

Revision ID: b268efdb349d
Revises: 45316ea4bcce
Create Date: 2024-04-11 21:04:53.810536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b268efdb349d'
down_revision: Union[str, None] = '45316ea4bcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestedRide', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suggestedRide', 'user', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggestedRide', type_='foreignkey')
    op.drop_column('suggestedRide', 'driver_id')
    # ### end Alembic commands ###
