"""sixth commit (add finished_ride to Ride table)

Revision ID: fa8820b7740e
Revises: 4e203bd56941
Create Date: 2024-04-14 21:14:36.422349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8820b7740e'
down_revision: Union[str, None] = '4e203bd56941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('finished_ride', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'finished_ride')
    # ### end Alembic commands ###
